using System;

namespace Hrimsoft.SqlBulk.PostgreSql
{
    /// <summary>
    /// Exception generated by the logic level of SqlBulkService
    /// </summary>
    public class SqlBulkServiceException: Exception
    {
        public SqlBulkServiceException(string message) :base(message) { }

        public SqlBulkServiceException(string message, Exception innerException)
        :base(message, innerException) { }
    }
}