using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels;
using Microsoft.Extensions.Logging.Abstractions;
using Npgsql;
using NUnit.Framework;

namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.BulkInsert
{
    public class BulkInsertIntegrationTests
    {
        private readonly TestConfiguration _configuration;

        public BulkInsertIntegrationTests()
        {
            _configuration = new TestConfiguration();
        }

        [SetUp]
        public async Task SetUp()
        {
            var truncateTableCmd = "truncate \"unit_tests\".\"simple_test_entity\";";
            var resetIdSequenceCmd = "ALTER SEQUENCE \"unit_tests\".\"simple_test_entity_id_seq\" RESTART WITH 1;";
            using (var connection = new NpgsqlConnection(_configuration.ConnectionString))
            using (var command = new NpgsqlCommand($"{truncateTableCmd}{resetIdSequenceCmd}", connection))
            {
                await connection.OpenAsync();
                await command.ExecuteNonQueryAsync();
            }
        }

        [Test]
        public async Task Insert_should_update_autogenerated_fields()
        {
            var bulkServiceOptions = new BulkServiceOptions();
            bulkServiceOptions.AddEntityProfile<TestEntity>(new SimpleEntityProfile());

            var insertCommandBuilder = new InsertSqlCommandBuilder(NullLoggerFactory.Instance);
            var updateCommandBuilder = new UpdateSqlCommandBuilder(NullLoggerFactory.Instance);

            var testService = new NpgsqlCommandsBulkService(bulkServiceOptions, NullLoggerFactory.Instance, insertCommandBuilder, updateCommandBuilder);

            var elements = new List<TestEntity>
            {
                new TestEntity {RecordId = "rec-01", SensorId = "sens-01", Value = 127},
                new TestEntity {RecordId = "rec-02", SensorId = "sens-01", Value = 128},
                new TestEntity {RecordId = "rec-01", SensorId = "sens-02", Value = 227},
                new TestEntity {RecordId = "rec-02", SensorId = "sens-02", Value = 228}
            };
            using (var connection = new NpgsqlConnection(_configuration.ConnectionString))
            {
                await testService.InsertAsync(connection, elements, CancellationToken.None);
            }

            Assert.AreEqual(1, elements[0].Id);
            Assert.AreEqual("rec-01", elements[0].RecordId);
            Assert.AreEqual("sens-01", elements[0].SensorId);
            Assert.AreEqual(127, elements[0].Value);
            
            Assert.AreEqual(2, elements[1].Id);
            Assert.AreEqual("rec-02", elements[1].RecordId);
            Assert.AreEqual("sens-01", elements[1].SensorId);
            Assert.AreEqual(128, elements[1].Value);
            
            Assert.AreEqual(3, elements[2].Id);
            Assert.AreEqual("rec-01", elements[2].RecordId);
            Assert.AreEqual("sens-02", elements[2].SensorId);
            Assert.AreEqual(227, elements[2].Value);

            Assert.AreEqual(4, elements[3].Id);
            Assert.AreEqual("rec-02", elements[3].RecordId);
            Assert.AreEqual("sens-02", elements[3].SensorId);
            Assert.AreEqual(228, elements[3].Value);
        }
        
        [Test]
        public async Task Insert_should_split_correctly_even_number_of_elements()
        {
            var bulkServiceOptions = new BulkServiceOptions(2);
            bulkServiceOptions.AddEntityProfile<TestEntity>(new SimpleEntityProfile());

            var insertCommandBuilder = new InsertSqlCommandBuilder(NullLoggerFactory.Instance);
            var updateCommandBuilder = new UpdateSqlCommandBuilder(NullLoggerFactory.Instance);

            var testService = new NpgsqlCommandsBulkService(bulkServiceOptions, NullLoggerFactory.Instance, insertCommandBuilder, updateCommandBuilder);

            var elements = new List<TestEntity>
            {
                new TestEntity {RecordId = "rec-01", SensorId = "sens-01", Value = 127},
                new TestEntity {RecordId = "rec-02", SensorId = "sens-01", Value = 128},
                new TestEntity {RecordId = "rec-01", SensorId = "sens-02", Value = 227},
                new TestEntity {RecordId = "rec-02", SensorId = "sens-02", Value = 228}
            };
            using (var connection = new NpgsqlConnection(_configuration.ConnectionString))
            {
                await testService.InsertAsync(connection, elements, CancellationToken.None);
            }

            Assert.AreEqual(1, elements[0].Id);
            Assert.AreEqual("rec-01", elements[0].RecordId);
            Assert.AreEqual("sens-01", elements[0].SensorId);
            Assert.AreEqual(127, elements[0].Value);
            
            Assert.AreEqual(2, elements[1].Id);
            Assert.AreEqual("rec-02", elements[1].RecordId);
            Assert.AreEqual("sens-01", elements[1].SensorId);
            Assert.AreEqual(128, elements[1].Value);
            
            Assert.AreEqual(3, elements[2].Id);
            Assert.AreEqual("rec-01", elements[2].RecordId);
            Assert.AreEqual("sens-02", elements[2].SensorId);
            Assert.AreEqual(227, elements[2].Value);

            Assert.AreEqual(4, elements[3].Id);
            Assert.AreEqual("rec-02", elements[3].RecordId);
            Assert.AreEqual("sens-02", elements[3].SensorId);
            Assert.AreEqual(228, elements[3].Value);
        }
        
        [Test]
        public async Task Insert_should_split_correctly_odd_number_of_elements()
        {
            var bulkServiceOptions = new BulkServiceOptions(2);
            bulkServiceOptions.AddEntityProfile<TestEntity>(new SimpleEntityProfile());

            var insertCommandBuilder = new InsertSqlCommandBuilder(NullLoggerFactory.Instance);
            var updateCommandBuilder = new UpdateSqlCommandBuilder(NullLoggerFactory.Instance);

            var testService = new NpgsqlCommandsBulkService(bulkServiceOptions, NullLoggerFactory.Instance, insertCommandBuilder, updateCommandBuilder);

            var elements = new List<TestEntity>
            {
                new TestEntity {RecordId = "rec-01", SensorId = "sens-01", Value = 127},
                new TestEntity {RecordId = "rec-02", SensorId = "sens-01", Value = 128},
                new TestEntity {RecordId = "rec-01", SensorId = "sens-02", Value = 227},
                new TestEntity {RecordId = "rec-02", SensorId = "sens-02", Value = 228},
                new TestEntity {RecordId = "rec-03", SensorId = "sens-02", Value = 229}
            };
            using (var connection = new NpgsqlConnection(_configuration.ConnectionString))
            {
                await testService.InsertAsync(connection, elements, CancellationToken.None);
            }

            Assert.AreEqual(1, elements[0].Id);
            Assert.AreEqual("rec-01", elements[0].RecordId);
            Assert.AreEqual("sens-01", elements[0].SensorId);
            Assert.AreEqual(127, elements[0].Value);
            
            Assert.AreEqual(2, elements[1].Id);
            Assert.AreEqual("rec-02", elements[1].RecordId);
            Assert.AreEqual("sens-01", elements[1].SensorId);
            Assert.AreEqual(128, elements[1].Value);
            
            Assert.AreEqual(3, elements[2].Id);
            Assert.AreEqual("rec-01", elements[2].RecordId);
            Assert.AreEqual("sens-02", elements[2].SensorId);
            Assert.AreEqual(227, elements[2].Value);

            Assert.AreEqual(4, elements[3].Id);
            Assert.AreEqual("rec-02", elements[3].RecordId);
            Assert.AreEqual("sens-02", elements[3].SensorId);
            Assert.AreEqual(228, elements[3].Value);

            Assert.AreEqual(5, elements[4].Id);
            Assert.AreEqual("rec-03", elements[4].RecordId);
            Assert.AreEqual("sens-02", elements[4].SensorId);
            Assert.AreEqual(229, elements[4].Value);
        }
    }
}