using System;
using JetBrains.Annotations;

namespace Hrimsoft.SqlBulk.PostgreSql
{
    /// <summary>
    /// Exception generated by the logic level of SqlBulkService
    /// </summary>
    public class SqlBulkServiceException: Exception
    {
        /// <inheritdoc />
        public SqlBulkServiceException(string message) :base(message) { }

        /// <inheritdoc />
        public SqlBulkServiceException(string message, [NotNull] Exception innerException)
        :base(message, innerException) { }

        /// <inheritdoc />
        public SqlBulkServiceException([NotNull] Exception innerException)
            :base(innerException.Message, innerException) { }
    }
}