using Hrimsoft.PostgresSqlBulkService;

namespace Healbe.PostgreSqlBulkService.Tests.TestModels
{
    public class SimpleEntityProfile: EntityProfile
    {
        public SimpleEntityProfile(int maximumSentElements=0)
            :base(typeof(TestEntity))
        {
            this.MaximumSentElements = maximumSentElements;

            this.HasProperty<TestEntity, int>(entity => entity.Id)
                .ThatIsAutoGeneratedPrivateKey();
            this.HasProperty<TestEntity, string>(entity => entity.RecordId)
                .ThatIsPartOfKey();
            this.HasProperty<TestEntity, string>(entity => entity.SensorId)
                .ThatIsPartOfKey();
            this.HasProperty<TestEntity, int>(entity => entity.Value);
        }
    }
}