using System.Data;

namespace Hrimsoft.SqlBulk.PostgreSql.Tests.TestModels
{
    public class SimpleEntityProfile: EntityProfile
    {
        public SimpleEntityProfile(int maximumSentElements=0)
            :base(typeof(TestEntity))
        {
            this.MaximumSentElements = maximumSentElements;

            this.HasProperty<TestEntity, int>(entity => entity.Id)
                .ThatIsAutoGeneratedPrivateKey()
                .HasColumnType(DbType.Int32);
            this.HasProperty<TestEntity, string>(entity => entity.RecordId)
                .HasColumnType(DbType.String);
            this.HasProperty<TestEntity, string>(entity => entity.SensorId)
                .HasColumnType(DbType.String);
            this.HasProperty<TestEntity, int>(entity => entity.Value)
                .HasColumnType(DbType.Int32);
        }
    }
}