using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Hrimsoft.SqlBulk.PostgreSql
{
    /// <summary>
    /// Sql bulk upset command generator 
    /// </summary>
    public class UpsertSqlCommandBuilder : IUpsertSqlCommandBuilder
    {
        private readonly ILogger<UpsertSqlCommandBuilder> _logger;

        /// <summary> </summary>
        public UpsertSqlCommandBuilder(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<UpsertSqlCommandBuilder>();
        }

        /// <summary>
        /// Generates sql upset command for bunch of elements
        /// </summary>
        /// <param name="elements">elements that have to be upserted</param>
        /// <param name="entityProfile">elements type profile (contains mapping and other options)</param>
        /// <param name="cancellationToken"></param>
        /// <returns>Returns a text of an sql upset command and collection of database parameters</returns>
        public IList<SqlCommandBuilderResult> Generate<TEntity>(ICollection<TEntity> elements, EntityProfile entityProfile, CancellationToken cancellationToken)
            where TEntity : class
        {
            if (elements == null)
                throw new ArgumentNullException(nameof(elements));
            if (entityProfile == null)
                throw new ArgumentNullException(nameof(entityProfile));

            if (elements.Count == 0)
                throw new ArgumentException("There is no elements in the collection. At least one element must be.", nameof(elements));

            _logger.LogTrace($"Generating upsert sql for {elements.Count} elements.");

            if (entityProfile.UniqueConstraint == null)
                throw new ArgumentException($"There is no unique constraint defined in the {entityProfile.GetType().FullName}", nameof(entityProfile));
            if (entityProfile.UniqueConstraint.UniqueProperties.All(p => p == null))
                throw new ArgumentException($"There is no unique properties defined in the {entityProfile.GetType().FullName}", nameof(entityProfile));

            var result = new List<SqlCommandBuilderResult>();

            if (_logger.IsEnabled(LogLevel.Debug))
            {
                _logger.LogDebug($"{nameof(TEntity)}: {typeof(TEntity).FullName}");
                _logger.LogDebug($"{nameof(elements)}.Count: {elements.Count}");
            }

            var (columns, returningClause, upsertClause) = this.GenerateClauses(entityProfile);
            var hasReturningClause = !string.IsNullOrWhiteSpace(returningClause);
            cancellationToken.ThrowIfCancellationRequested();

            const int MAX_PARAMS_PER_CMD = 65_535;

            var commandHeader = $"insert into {entityProfile.TableName} ({columns}) values ";
            var entireCommandLength = commandHeader.Length
                                    + (returningClause?.Length ?? 0)
                                    + columns.Length * elements.Count;

            if (_logger.IsEnabled(LogLevel.Debug))
                _logger.LogDebug($"approximateEntireCommandLength: {entireCommandLength}");

            var approximateParamsCount = elements.Count * entityProfile.Properties.Count;
            var commandParameters      = new List<NpgsqlParameter>(approximateParamsCount);
            var resultBuilder          = new StringBuilder(entireCommandLength);
            resultBuilder.Append(commandHeader);
            var elementIndex = -1;
            using (var elementsEnumerator = elements.GetEnumerator())
            {
                while (elementsEnumerator.MoveNext())
                {
                    var item = elementsEnumerator.Current;
                    if (item == null)
                        continue;

                    var paramsPerElement = 0;
                    elementIndex++;
                    cancellationToken.ThrowIfCancellationRequested();

                    resultBuilder.Append('(');
                    var firstPropertyValue = true;
                    foreach (var propInfo in entityProfile.Properties.Values)
                    {
                        if (propInfo.IsAutoGenerated)
                            continue;
                        var delimiter = firstPropertyValue ? "" : ", ";
                        resultBuilder.Append(delimiter);
                        var propValue = propInfo.GetPropertyValueAsString(item);
                        if (propValue == null)
                        {
                            var paramName = $"@param_{propInfo.DbColumnName}_{elementIndex}";
                            try
                            {
                                commandParameters.Add(new NpgsqlParameter(paramName, propInfo.DbColumnType)
                                                      {
                                                          Value      = propInfo.GetPropertyValue(item) ?? DBNull.Value,
                                                          IsNullable = propInfo.IsNullable
                                                      });
                                paramsPerElement++;
                            }
                            catch (Exception ex)
                            {
                                var message = $"an error occurred while calculating a {paramName}";
                                throw new SqlGenerationException(SqlOperation.Upsert, message, ex);
                            }
                            resultBuilder.Append(paramName);
                        }
                        else
                        {
                            resultBuilder.Append(propValue);
                        }
                        firstPropertyValue = false;
                    }
                    resultBuilder.Append(')');
                    if (commandParameters.Count + paramsPerElement > MAX_PARAMS_PER_CMD)
                    {
                        if (hasReturningClause)
                        {
                            resultBuilder.AppendLine(upsertClause);
                            resultBuilder.Append(" returning ");
                            resultBuilder.Append(returningClause);
                        }
                        else
                            resultBuilder.Append(upsertClause);
                        resultBuilder.Append(";");
                        result.Add(new SqlCommandBuilderResult
                                   {
                                       Command                = resultBuilder.ToString(),
                                       Parameters             = commandParameters,
                                       IsThereReturningClause = hasReturningClause
                                   });
                        var remainingParams = (elements.Count - elementIndex - 1) * paramsPerElement;
                        commandParameters = new List<NpgsqlParameter>(Math.Min(remainingParams, MAX_PARAMS_PER_CMD));
                        resultBuilder.Clear();
                        resultBuilder.Append(commandHeader);
                    }
                    else
                    {
                        //  Finished with properties 
                        if (elements.Count > 1 && elementIndex < elements.Count - 1)
                            resultBuilder.Append(", ");
                    }
                }
            }
            if (elementIndex == -1)
                throw new ArgumentException("There is no elements in the collection. At least one element must be.", nameof(elements));
            if (hasReturningClause)
            {
                resultBuilder.AppendLine(upsertClause);
                resultBuilder.Append(" returning ");
                resultBuilder.Append(returningClause);
            }
            else
                resultBuilder.Append(upsertClause);
            resultBuilder.Append(";");
            result.Add(new SqlCommandBuilderResult
                       {
                           Command                = resultBuilder.ToString(),
                           Parameters             = commandParameters,
                           IsThereReturningClause = hasReturningClause
                       });
            return result;
        }

        /// <summary>
        /// In one pass generates both columns and returning clauses 
        /// </summary>
        /// <param name="entityProfile">elements type profile (contains mapping and other options)</param>
        /// <returns>
        /// Returns named tuple with generated columns, returning and upsert clauses.
        /// If there is no properties that has to be included into returning clause then ReturningClause item in the result tuple will be an empty string.
        /// </returns>
        // ReSharper disable once MemberCanBePrivate.Global  Needed to be public for unit testing purpose
        public (string Columns, string ReturningClause, string UpsertClause) GenerateClauses(EntityProfile entityProfile)
        {
            if (entityProfile == null)
                throw new ArgumentNullException(nameof(entityProfile));

            var properties           = entityProfile.Properties.Values;
            var upsertClause         = GenerateOnConflictClause(entityProfile.UniqueConstraint);
            var firstUpdateSetColumn = true;

            var returningClause      = "";
            var firstReturningColumn = true;

            var columns     = "";
            var firstColumn = true;
            foreach (var propInfo in properties)
            {
                if (propInfo.IsUpdatedAfterInsert || propInfo.IsUpdatedAfterUpdate)
                {
                    var returningDelimiter = firstReturningColumn ? "" : ", ";
                    returningClause      += $"{returningDelimiter}\"{propInfo.DbColumnName}\"";
                    firstReturningColumn =  false;
                }
                if (propInfo.IsAutoGenerated)
                    continue;
                if (!propInfo.IsPartOfUniqueConstraint)
                {
                    var upsertSetDelimiter = firstUpdateSetColumn ? " do update set " : ", ";
                    upsertClause         += $"{upsertSetDelimiter}\"{propInfo.DbColumnName}\" = {entityProfile.TableName}.\"{propInfo.DbColumnName}\"";
                    firstUpdateSetColumn =  false;
                }
                var delimiter = firstColumn ? "" : ", ";
                columns     += $"{delimiter}\"{propInfo.DbColumnName}\"";
                firstColumn =  false;
            }
            if (_logger.IsEnabled(LogLevel.Debug))
            {
                _logger.LogDebug($"columns: {columns}");
                _logger.LogDebug($"upsertClause: {upsertClause}");
                _logger.LogDebug($"returningClause: {returningClause}");
            }
            return (columns, returningClause, upsertClause);
        }

        /// <summary>
        /// Generate on conflict clause
        /// </summary>
        /// <param name="uniqueConstraintInfo"></param>
        /// <returns></returns>
        public string GenerateOnConflictClause(EntityUniqueConstraint uniqueConstraintInfo)
        {
            if (uniqueConstraintInfo == null)
                throw new ArgumentNullException(nameof(uniqueConstraintInfo));

            var result = " on conflict ";
            if (string.IsNullOrWhiteSpace(uniqueConstraintInfo.Name))
            {
                var firstProperty = uniqueConstraintInfo.UniqueProperties.FirstOrDefault(p => p != null);
                if (firstProperty == null)
                    throw new SqlGenerationException(SqlOperation.Upsert,
                                                     "It is impossible to generate a constraint name as neither it as set in constructor nor properties have been set as a part of unique constraint.");
                result += $"(\"{firstProperty.DbColumnName}\")";
            }
            else
            {
                result += $"on constraint \"{uniqueConstraintInfo.Name}\"";
            }
            return result;
        }
    }
}