namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class BulkEntityProfile: EntityProfile
    {
        public BulkEntityProfile(int maximumSentElements=0)
            :base(typeof(TestEntity))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("bulk_test_entity", "unit_tests");

            this.HasProperty<TestEntity, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasProperty<TestEntity, string>(entity => entity.RecordId);
            this.HasProperty<TestEntity, string>(entity => entity.SensorId);
            this.HasProperty<TestEntity, int>(entity => entity.Value);
        }
    }
}