using System.Data;

namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class EntityWithIntegerEnumProfile: EntityProfile
    {
        public EntityWithIntegerEnumProfile(int maximumSentElements=0)
            :base(typeof(TestEntityWithEnum))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("entity_with_int_enum", "unit_tests");

            this.HasProperty<TestEntityWithEnum, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasProperty<TestEntityWithEnum, SomeEnum>(entity => entity.SomeEnumValue);
        }
    }
}