using System.Data;

namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class EntityWithIntegerEnumProfile: EntityProfile
    {
        public EntityWithIntegerEnumProfile(int maximumSentElements=0)
            :base(typeof(TestEntityWithIntEnum))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("entity_with_int_enum", "unit_tests");

            this.HasProperty<TestEntityWithIntEnum, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasProperty<TestEntityWithIntEnum, SomeEnum>(entity => entity.SomeEnumValue);
        }
    }
}