namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class EntityWithNullableProfile: EntityProfile
    {
        public EntityWithNullableProfile(int maximumSentElements=0)
            :base(typeof(TestEntityWithNullables))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("nullable_test_entity", "unit_tests");

            this.HasProperty<TestEntityWithNullables, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
        }
    }
}