namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class EntityWithNullableProfile: EntityProfile
    {
        public EntityWithNullableProfile(int maximumSentElements=0)
            :base(typeof(EntityWithNullableProperty))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("simple_test_entity", "unit_tests");

            this.HasProperty<EntityWithNullableProperty, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasProperty<EntityWithNullableProperty, string>(entity => entity.RecordId);
            this.HasProperty<EntityWithNullableProperty, string>(entity => entity.SensorId);
            this.HasProperty<EntityWithNullableProperty, int?>("value", entity => entity.Value);
        }
    }
}