using System;
using Hrimsoft.Core.ValueObjects;

namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class EntityWithDatesProfile : EntityProfile
    {
        public EntityWithDatesProfile(int maximumSentElements = 0)
            : base(typeof(EntityWithDates))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("entity_with_dates", "unit_tests");

            this.HasProperty<EntityWithDates, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasProperty<EntityWithDates, Date>(entity => entity.Date);
            this.HasProperty<EntityWithDates, DateTime>("dt", entity => entity.DateAndTime);
            this.HasProperty<EntityWithDates, DateTimeOffset>("dt_offset", entity => entity.DateTimeAndOffset);
        }
    }
}