namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    public class EntityWithStringEnumProfile: EntityProfile
    {
        public EntityWithStringEnumProfile(int maximumSentElements=0)
            :base(typeof(TestEntityWithStrEnum))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("entity_with_str_enum", "unit_tests");

            this.HasProperty<TestEntityWithStrEnum, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasProperty<TestEntityWithStrEnum, SomeEnum>(entity => entity.SomeEnumValue);
        }
    }
}