using System.Data;

namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    /// <summary>
    /// Entity profile that defines properties that
    ///  - have unique constraint
    ///  - have to be included into the returning clause
    /// </summary>
    public class UpsertEntityProfile: EntityProfile
    {
        public UpsertEntityProfile(int maximumSentElements=0)
            :base(typeof(TestEntity))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("entity_with_unique_columns", "unit_tests");
            
            this.HasUniqueConstraint("business_identity");
            
            this.HasProperty<TestEntity, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasPropertyAsPartOfUniqueConstraint<TestEntity, string>(entity => entity.RecordId);
            this.HasPropertyAsPartOfUniqueConstraint<TestEntity, string>(entity => entity.SensorId);
            this.HasProperty<TestEntity, int>(entity => entity.Value);
        }
    }
}