using System.Data;

namespace Hrimsoft.SqlBulk.PostgreSql.IntegrationTests.TestModels
{
    /// <summary>
    /// Entity profile that defines properties that
    ///  - have unique constraint
    ///  - have to be included into the returning clause
    /// </summary>
    public class UpsertEntityProfile : EntityProfile
    {
        public UpsertEntityProfile(int maximumSentElements = 0)
            : base(typeof(TestEntity))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("entity_with_unique_columns", "unit_tests");

            // The name of unique constraint.
            // This is the most important part of upsert declaration
            this.HasUniqueConstraint("business_identity");

            this.HasProperty<TestEntity, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();

            // the first possibility how to declare a property as a part of a unique constraint
            this.HasPropertyAsPartOfUniqueConstraint<TestEntity, string>(entity => entity.RecordId);
            this.HasPropertyAsPartOfUniqueConstraint<TestEntity, string>(entity => entity.SensorId);

            this.HasProperty<TestEntity, int>(entity => entity.Value);
            this.HasProperty<TestEntity, int?>("nullable_value", entity => entity.NullableValue);
        }
    }
}