using System;
using System.Data;
using System.Linq.Expressions;
using JetBrains.Annotations;

namespace Hrimsoft.SqlBulk.PostgreSql
{
    /// <summary>
    /// A configuration of an entity's property mapping
    /// </summary>
    public class PropertyProfile
    {
        /// <inheritdoc />
        public PropertyProfile(string column, [NotNull] Expression propertyExpression)
        {
            if (string.IsNullOrWhiteSpace(column))
                throw new ArgumentNullException(nameof(column));
            
            this.DbColumnName = column;
            this.PropertyExpression = propertyExpression;
        }
        
        /// <summary>
        /// If true then the value of the column that represents this property will be included after insert
        /// </summary>
        public bool IncludeInReturning { get; private set; }

        /// <summary>
        /// If true this property is a private key 
        /// </summary>
        public bool IsAutoGeneratedKey { get; private set; }
        
        /// <summary>
        /// Expression to access a property 
        /// </summary>
        public Expression PropertyExpression { get; }

        /// <summary>
        /// Column name in database table 
        /// </summary>
        public string DbColumnName { get; }
        
        /// <summary>
        /// Database column type
        /// </summary>
        public DbType DbColumnType { get; private set;  }
        
        /// <summary>
        /// When applied, the value of the column that represents this property will be included after insert in returning clause
        /// and then auto generated id values will be mapped on entities that have such properties as a key.
        /// </summary>
        public PropertyProfile ThatIsPartOfKey()
        {
            this.IncludeInReturning = true;
            return this;
        }
        
        /// <summary>
        /// When applied, the value of a new generated private key  that represents this property will be updated after insert
        /// </summary>
        public PropertyProfile ThatIsAutoGeneratedPrivateKey()
        {
            this.IsAutoGeneratedKey = true;
            this.IncludeInReturning = true;
            
            return this;
        }

        /// <summary>
        /// Defines which database column type should be used for this property
        /// </summary>
        public PropertyProfile HasColumnType([NotNull] DbType columnType)
        {
            this.DbColumnType = columnType;
            return this;
        } 
    }
}