using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Hrimsoft.SqlBulk.PostgreSql.Attributes;

namespace Hrimsoft.SqlBulk.PostgreSql.Tests.TestModels
{
    [Table("annotated_entities", Schema = "unit_tests")]
    public class AnnotatedEntity
    {
        [Key, AutoGenerated]
        public int Id { get; set; }
        
        [Column("record", TypeName = "text")]
        [PartOfUniqueConstraint]
        public string Record { get; set; } 
        
        [DataType(DataType.Text)]
        [PartOfUniqueConstraint]
        public string SensorId { get; set; }

        public long Value { get; set; }
        
        [UpdateAfterInsert]
        public long ValueGeneratedOnInsert { get; set; }
        
        [UpdateAfterUpdate]
        public long ValueGeneratedOnUpdate { get; set; }
        
        [NotMapped]
        public long AbstractValue { get; set; }
    }
}