using System.Data;

namespace Hrimsoft.SqlBulk.PostgreSql.Tests.TestModels
{
    /// <summary>
    /// Entity profile that defines properties that have to be included into the returning clause
    /// </summary>
    public class ReturningEntityProfile: EntityProfile
    {
        public ReturningEntityProfile(int maximumSentElements=0)
            :base(typeof(TestEntity))
        {
            this.MaximumSentElements = maximumSentElements;

            this.ToTable("simple_test_entity", "unit_tests");

            this.HasProperty<TestEntity, int>(entity => entity.Id)
                .ThatIsAutoGenerated()
                .ThatIsPrivateKey();
            this.HasPropertyAsPartOfUniqueConstraint<TestEntity, string>(entity => entity.RecordId)
                .MustBeUpdatedAfterInsert()
                .MustBeUpdatedAfterUpdate();
            this.HasPropertyAsPartOfUniqueConstraint<TestEntity, string>(entity => entity.SensorId)
                .MustBeUpdatedAfterInsert();
            this.HasProperty<TestEntity, int>(entity => entity.IntValue)
                .MustBeUpdatedAfterUpdate();
        }
    }
}